/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as DeathSubjectIdRouteImport } from './routes/death.$subjectId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AccountDeleteRouteImport } from './routes/account_.delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DeathSubjectIdRoute = DeathSubjectIdRouteImport.update({
  id: '/death/$subjectId',
  path: '/death/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account_/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/connections': typeof ConnectionsRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/account/delete': typeof AccountDeleteRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/connections': typeof ConnectionsRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/account/delete': typeof AccountDeleteRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/connections': typeof ConnectionsRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/account_/delete': typeof AccountDeleteRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/connections'
    | '/messages'
    | '/preview'
    | '/account/delete'
    | '/api/$'
    | '/death/$subjectId'
    | '/join/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/connections'
    | '/messages'
    | '/preview'
    | '/account/delete'
    | '/api/$'
    | '/death/$subjectId'
    | '/join/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/connections'
    | '/messages'
    | '/preview'
    | '/account_/delete'
    | '/api/$'
    | '/death/$subjectId'
    | '/join/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  ConnectionsRoute: typeof ConnectionsRoute
  MessagesRoute: typeof MessagesRoute
  PreviewRoute: typeof PreviewRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DeathSubjectIdRoute: typeof DeathSubjectIdRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/death/$subjectId': {
      id: '/death/$subjectId'
      path: '/death/$subjectId'
      fullPath: '/death/$subjectId'
      preLoaderRoute: typeof DeathSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/delete': {
      id: '/account_/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  ConnectionsRoute: ConnectionsRoute,
  MessagesRoute: MessagesRoute,
  PreviewRoute: PreviewRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  ApiSplatRoute: ApiSplatRoute,
  DeathSubjectIdRoute: DeathSubjectIdRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
