/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppWatchRouteImport } from './routes/_app.watch'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppConnectionsRouteImport } from './routes/_app.connections'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppDeathSubjectIdRouteImport } from './routes/_app.death.$subjectId'
import { Route as AppAccountDeleteRouteImport } from './routes/_app.account_.delete'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeathSubjectIdRoute = AppDeathSubjectIdRouteImport.update({
  id: '/death/$subjectId',
  path: '/death/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountDeleteRoute = AppAccountDeleteRouteImport.update({
  id: '/account_/delete',
  path: '/account/delete',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/connections': typeof AppConnectionsRoute
  '/me': typeof AppMeRoute
  '/messages': typeof AppMessagesRoute
  '/watch': typeof AppWatchRoute
  '/api/$': typeof ApiSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/account/delete': typeof AppAccountDeleteRoute
  '/death/$subjectId': typeof AppDeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/connections': typeof AppConnectionsRoute
  '/me': typeof AppMeRoute
  '/messages': typeof AppMessagesRoute
  '/watch': typeof AppWatchRoute
  '/api/$': typeof ApiSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/account/delete': typeof AppAccountDeleteRoute
  '/death/$subjectId': typeof AppDeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/me': typeof AppMeRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/watch': typeof AppWatchRoute
  '/api/$': typeof ApiSplatRoute
  '/join/$token': typeof JoinTokenRoute
  '/_app/account_/delete': typeof AppAccountDeleteRoute
  '/_app/death/$subjectId': typeof AppDeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/preview'
    | '/account'
    | '/activity'
    | '/connections'
    | '/me'
    | '/messages'
    | '/watch'
    | '/api/$'
    | '/join/$token'
    | '/account/delete'
    | '/death/$subjectId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/preview'
    | '/account'
    | '/activity'
    | '/connections'
    | '/me'
    | '/messages'
    | '/watch'
    | '/api/$'
    | '/join/$token'
    | '/account/delete'
    | '/death/$subjectId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/preview'
    | '/_app/account'
    | '/_app/activity'
    | '/_app/connections'
    | '/_app/me'
    | '/_app/messages'
    | '/_app/watch'
    | '/api/$'
    | '/join/$token'
    | '/_app/account_/delete'
    | '/_app/death/$subjectId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  ApiSplatRoute: typeof ApiSplatRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/death/$subjectId': {
      id: '/_app/death/$subjectId'
      path: '/death/$subjectId'
      fullPath: '/death/$subjectId'
      preLoaderRoute: typeof AppDeathSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account_/delete': {
      id: '/_app/account_/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AppAccountDeleteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppMeRoute: typeof AppMeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppWatchRoute: typeof AppWatchRoute
  AppAccountDeleteRoute: typeof AppAccountDeleteRoute
  AppDeathSubjectIdRoute: typeof AppDeathSubjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppMeRoute: AppMeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppWatchRoute: AppWatchRoute,
  AppAccountDeleteRoute: AppAccountDeleteRoute,
  AppDeathSubjectIdRoute: AppDeathSubjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  ApiSplatRoute: ApiSplatRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
