/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeathSubjectIdRouteImport } from './routes/death.$subjectId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeathSubjectIdRoute = DeathSubjectIdRouteImport.update({
  id: '/death/$subjectId',
  path: '/death/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/preview': typeof PreviewRoute
  '/api/$': typeof ApiSplatRoute
  '/death/$subjectId': typeof DeathSubjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/messages'
    | '/preview'
    | '/api/$'
    | '/death/$subjectId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/messages'
    | '/preview'
    | '/api/$'
    | '/death/$subjectId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/messages'
    | '/preview'
    | '/api/$'
    | '/death/$subjectId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessagesRoute: typeof MessagesRoute
  PreviewRoute: typeof PreviewRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DeathSubjectIdRoute: typeof DeathSubjectIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/death/$subjectId': {
      id: '/death/$subjectId'
      path: '/death/$subjectId'
      fullPath: '/death/$subjectId'
      preLoaderRoute: typeof DeathSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessagesRoute: MessagesRoute,
  PreviewRoute: PreviewRoute,
  ApiSplatRoute: ApiSplatRoute,
  DeathSubjectIdRoute: DeathSubjectIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
